"""
documents.py — loads the SEC 10-K filing excerpts.

In this project we use 3 hardcoded Apple 10-K sections as demo data.
In production you would replace load_documents() to read real PDFs from disk
or Azure Blob Storage — everything downstream stays identical.
"""

from langchain_core.documents import Document


# ─── Sample 10-K data (Apple FY2023) ──────────────────────────────────────────
SAMPLE_DOCS = [
    {
        "source": "Apple_10K_2023_Risk",
        "text": """RISK FACTORS
Apple's operations and financial results are subject to various risks and uncertainties.
Global and regional economic conditions, including conditions resulting from financial and credit market fluctuations,
can adversely affect demand for Apple's products and services.
Apple faces intense competition in all of its business areas from well-established companies with significant
resources, as well as from new market entrants.
Apple depends on the performance of distributors, carriers, wholesalers and other resellers.
The Company's fiscal year 2023 revenue was $383.3 billion, compared to $394.3 billion in fiscal 2022,
a decrease of approximately 2.8 percent.
The Company's net income for fiscal 2023 was $97.0 billion, or $6.13 diluted earnings per share,
compared to $99.8 billion, or $6.11 diluted earnings per share, in fiscal 2022.
Apple's gross margin percentage was 44.1% in fiscal 2023, compared to 43.3% in fiscal 2022.
Services revenue reached an all-time high of $85.2 billion in fiscal 2023, up 9 percent year over year."""
    },
    {
        "source": "Apple_10K_2023_Products",
        "text": """PRODUCTS AND SERVICES
Apple designs, manufactures and markets smartphones, personal computers, tablets, wearables and accessories.
iPhone is Apple's line of smartphones based on its iOS operating system.
iPhone net sales were $200.6 billion in fiscal 2023, representing approximately 52% of total revenue.
Mac net sales were $29.4 billion in fiscal 2023, down from $40.2 billion in fiscal 2022.
iPad net sales were $28.3 billion in fiscal 2023.
Wearables, Home and Accessories net sales were $39.8 billion in fiscal 2023.
Apple's Services segment includes advertising, AppleCare, cloud, digital content, payment and other services.
The App Store, Apple Music, Apple TV+, Apple Arcade, iCloud and Apple Pay are key Services offerings.
The Company had approximately 2.2 billion active devices at the end of fiscal year 2023."""
    },
    {
        "source": "Apple_10K_2023_Liquidity",
        "text": """LIQUIDITY AND CAPITAL RESOURCES
The Company believes its existing balances of cash, cash equivalents and unrestricted marketable securities,
together with cash generated by operations, will be sufficient to satisfy its expected cash needs.
Cash and cash equivalents as of September 30, 2023 were $29.965 billion.
Total marketable securities were $100.544 billion, consisting of current marketable securities of $31.590 billion
and non-current marketable securities of $100.544 billion.
During fiscal 2023, the Company returned over $77 billion to shareholders,
including $15.1 billion in dividends and dividend equivalents and $62.2 billion through repurchases of 471 million shares.
Capital expenditures were $10.959 billion in fiscal 2023.
The Company's long-term debt as of September 30, 2023 was $95.281 billion."""
    },
]


def load_documents() -> list[Document]:
    """
    Load 10-K excerpts and wrap them as LangChain Document objects.

    Returns:
        List of Document objects with page_content + metadata["source"]

    To use real PDFs instead, replace this function body with:
        from langchain_community.document_loaders import PyPDFLoader
        loader = PyPDFLoader("path/to/10k.pdf")
        return loader.load()
    """
    docs = [
        Document(
            page_content=d["text"],
            metadata={"source": d["source"]}
        )
        for d in SAMPLE_DOCS
    ]
    print(f"📂 Loaded {len(docs)} documents")
    for doc in docs:
        print(f"   - {doc.metadata['source']}: {len(doc.page_content)} characters")
    return docs
