# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmWAkkEFIcgO9M098kDD3684ekcW1Od6
"""

!pip install -q fastapi uvicorn structlog tenacity \
pybreaker prometheus-client \
prometheus-fastapi-instrumentator \
httpx pyngrok nest-asyncio requests

import nest_asyncio
nest_asyncio.apply()

import asyncio
import structlog
import uuid
import time
import threading
import httpx
import requests
import contextvars

from collections import defaultdict

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from prometheus_client import Counter, Histogram, REGISTRY
from prometheus_fastapi_instrumentator import Instrumentator

from pyngrok import ngrok, conf

import uvicorn

# =========================================================
# STRUCTURED LOGGING
# =========================================================

structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
)

log = structlog.get_logger()

# =========================================================
# FASTAPI APP
# =========================================================

app = FastAPI(
    title="EY Payment API",
    version="1.0.0"
)

# =========================================================
# EXTENSION A — RATE LIMITING
# =========================================================

RATE_LIMIT = 5
WINDOW_SECONDS = 60

request_store = defaultdict(list)

# =========================================================
# EXTENSION B — CORRELATION ID PROPAGATION
# =========================================================

correlation_context = contextvars.ContextVar(
    "correlation_id",
    default=None
)

# =========================================================
# LOGGING + RATE LIMIT + CORRELATION MIDDLEWARE
# =========================================================

@app.middleware("http")
async def logging_middleware(request: Request, call_next):

    # -----------------------------
    # RATE LIMITING
    # -----------------------------

    client_ip = request.client.host

    current_time = time.time()

    request_store[client_ip] = [
        ts for ts in request_store[client_ip]
        if current_time - ts < WINDOW_SECONDS
    ]

    if len(request_store[client_ip]) >= RATE_LIMIT:

        return JSONResponse(
            status_code=429,
            content={
                "error": "Rate limit exceeded"
            },
            headers={
                "Retry-After": str(WINDOW_SECONDS)
            }
        )

    request_store[client_ip].append(current_time)

    # -----------------------------
    # CORRELATION ID
    # -----------------------------

    correlation_id = request.headers.get(
        "X-Correlation-Id",
        str(uuid.uuid4())
    )

    correlation_context.set(correlation_id)

    # -----------------------------
    # LOGGING
    # -----------------------------

    start = time.perf_counter()

    log.info(
        "request.started",
        path=request.url.path,
        method=request.method,
        correlation_id=correlation_id
    )

    response = await call_next(request)

    elapsed_ms = round(
        (time.perf_counter() - start) * 1000,
        2
    )

    log.info(
        "request.completed",
        path=request.url.path,
        status=response.status_code,
        latency_ms=elapsed_ms,
        correlation_id=correlation_id
    )

    response.headers["X-Correlation-Id"] = correlation_id

    return response

# =========================================================
# ROUTES
# =========================================================

@app.get("/health/live")
async def liveness():

    return {
        "status": "alive"
    }

@app.get("/health/ready")
async def readiness():

    return {
        "status": "ready",
        "db": "ok",
        "mq": "ok"
    }

@app.post("/payments")
async def create_payment(request: Request):

    body = await request.json()

    log.info(
        "payment.received",
        amount=body.get("amount"),
        currency=body.get("currency", "GBP")
    )

    return {
        "payment_id": str(uuid.uuid4()),
        "status": "accepted",
        **body
    }

print("Logging middleware and routes defined")

# =========================================================
# PROMETHEUS METRICS
# =========================================================

if 'payment_amount_gbp' not in REGISTRY._names_to_collectors:

    PAYMENT_AMOUNT = Histogram(
        'payment_amount_gbp',
        'Payment amount in GBP',
        buckets=[10, 50, 100, 500, 1000, 5000, 10000]
    )

if 'payment_errors_total' not in REGISTRY._names_to_collectors:

    ERROR_COUNT = Counter(
        'payment_errors_total',
        'Total payment processing errors',
        ['error_type']
    )

Instrumentator().instrument(app).expose(app)

print("Prometheus metrics instrumented")

# =========================================================
# CORRELATION PROPAGATION TEST
# =========================================================

async def outbound_call():

    correlation_id = correlation_context.get()

    if correlation_id is None:
        correlation_id = str(uuid.uuid4())

    headers = {
        "X-Correlation-Id": correlation_id
    }

    async with httpx.AsyncClient() as client:

        response = await client.get(
            "https://httpbin.org/headers",
            headers=headers
        )

        return response.json()

print("Correlation propagation enabled")

# =========================================================
# NGROK TOKEN
# =========================================================

NGROK_TOKEN = "3Et08KLYiQGjHkwaSzcMTEL3o8k_4rZRSZqSLSM8aS5g9TqJQ"

conf.get_default().auth_token = NGROK_TOKEN

# =========================================================
# RUN SERVER
# =========================================================

def run_server():

    config = uvicorn.Config(
        app=app,
        host="0.0.0.0",
        port=8000,
        log_level="warning"
    )

    server = uvicorn.Server(config)

    loop = asyncio.new_event_loop()

    asyncio.set_event_loop(loop)

    loop.run_until_complete(server.serve())

thread = threading.Thread(
    target=run_server,
    daemon=True
)

thread.start()

# =========================================================
# START NGROK
# =========================================================

time.sleep(3)

tunnel = ngrok.connect(8000)

public_url = tunnel.public_url

print("\n Public URL:", public_url)
print("Health:", public_url + "/health/ready")
print("Metrics:", public_url + "/metrics")
print("Docs:", public_url + "/docs")

BASE = public_url

time.sleep(2)

# =========================================================
# TEST HEALTH ENDPOINT
# =========================================================

with httpx.Client() as client:

    r = client.get(f"{BASE}/health/ready")

    print("\nHealth Check:")
    print(r.text)

# =========================================================
# TEST PAYMENT ENDPOINT
# =========================================================

with httpx.Client() as client:

    r = client.post(
        f"{BASE}/payments",
        json={
            "amount": 1500,
            "currency": "GBP",
            "account": "ACC-42"
        },
        headers={
            "X-Correlation-Id": "demo-corr-001"
        }
    )

    print("\n Payment API:")
    print(r.text)

# =========================================================
# TEST RATE LIMITING
# =========================================================

print("\n Testing Rate Limiting")

for i in range(7):

    r = requests.get(f"{BASE}/health/live")

    print(f"Request {i+1}: {r.status_code}")

# =========================================================
# TEST CORRELATION PROPAGATION
# =========================================================

result = asyncio.run(outbound_call())

print("\nCorrelation Propagation:")
print(result)

print("\n Extension A + B Completed Successfully")

